services:
  hardware-tools:
    build: .
    container_name: hardware-tools
    network_mode: host
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - /:/host:ro
      - /dev:/dev
      - /sys:/sys:ro